extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - "prettier"
  - "plugin:prettier/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  project: [
    "tsconfig.json",
    "tests/tsconfig.json",
  ]
plugins:
  - "@typescript-eslint"
  - "prettier"
root: true
rules:
  "@typescript-eslint/no-inferrable-types": "off"
  "@typescript-eslint/no-unused-vars":
    - error
    - argsIgnorePattern: _
      varsIgnorePattern: _
